export default {
  GET_CATEGORIES_IN_PROGRESS: 'GET_CATEGORIES_IN_PROGRESS',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  START_GAME_IN_PROCESS: 'START_GAME_IN_PROCESS',
  START_GAME_SUCCESS: 'START_GAME_SUCCESS',
  START_GAME_FAILURE: 'START_GAME_FAILURE',

  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',

  IS_GAME_OVER: 'IS_GAME_OVER',

  STYLE_BUTTONS: 'STYLE_BUTTONS',

  INCREMENT_ROUND: 'INCREMENT_ROUND',

  PAUSE_GAME: 'PAUSE_GAME',

  SCORE: 'SCORE',

  NEW_GAME: 'NEW_GAME'
}
